In [1]:
import pandas as pd
import numpy as np
import polars as pl

In [35]:
df_master = pl.read_csv("../data/master_file.csv")
df_master.head()

shape: (5, 40)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ date      ┆ symbol_15 ┆ sec_desc  ┆ cusip     ┆ … ┆ effective ┆ tron_ltse ┆ tron_memx ┆ tron_mia │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _date     ┆ ---       ┆ ---       ┆ x        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ i64       ┆ i64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2023-01-0 ┆ A         ┆ Agilent   ┆ 00846U101 ┆ … ┆ 1999-11-1 ┆ 0         ┆ 1         ┆ 1        │
│ 3         ┆           ┆ Technolog ┆           ┆   ┆ 8         ┆           ┆           ┆          │
│           ┆           ┆ ies Inc.  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-01-0 ┆ AA        ┆ Alcoa Cor ┆ 013872106 ┆ … ┆ 2016-10-1 ┆ 0         ┆ 1         ┆ 1        │
│ 3         ┆           ┆ poration  ┆           ┆   ┆ 8         ┆           ┆           ┆          │
│ 2023-01-0 ┆ AAA       ┆ AXS First ┆ 46144X610 ┆ … ┆ 2022-10-1 ┆ 0         ┆ 0         ┆ 0        │
│ 3         ┆           ┆ Priority  ┆           ┆   ┆ 7         ┆           ┆           ┆          │
│           ┆           ┆ CLO Bond  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ ET…       ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-01-0 ┆ AAAU      ┆ Goldman   ┆ 38150K103 ┆ … ┆ null      ┆ 0         ┆ 1         ┆ 1        │
│ 3         ┆           ┆ Sachs     ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Physical  ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ Gold ET…  ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2023-01-0 ┆ AAC       ┆ Ares Acqu ┆ G33032106 ┆ … ┆ 2021-03-2 ┆ 0         ┆ 1         ┆ 1        │
│ 3         ┆           ┆ isition   ┆           ┆   ┆ 5         ┆           ┆           ┆          │
│           ┆           ┆ Corporati ┆           ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆ on        ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [36]:
df_master['symbol_15'].unique().shape

(13101,)

In [37]:
df_master.describe()

shape: (9, 41)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ date      ┆ symbol_15 ┆ sec_desc  ┆ … ┆ effective ┆ tron_ltse ┆ tron_memx ┆ tron_mia │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _date     ┆ ---       ┆ ---       ┆ x        │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 2864764   ┆ 2864764   ┆ 2864764   ┆ … ┆ 1392403   ┆ 2.864764e ┆ 2.864764e ┆ 2.864764 │
│           ┆           ┆           ┆           ┆   ┆           ┆ 6         ┆ 6         ┆ e6       │
│ null_coun ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 1472361   ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.013266  ┆ 0.700164  ┆ 0.547762 │
│ std       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.114412  ┆ 0.458186  ┆ 0.497714 │
│ min       ┆ 2023-01-0 ┆ A         ┆ X-Square  ┆ … ┆ 1892-06-2 ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│           ┆ 3         ┆           ┆ Municipal ┆   ┆ 3         ┆           ┆           ┆          │
│           ┆           ┆           ┆ Income    ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Tax…      ┆   ┆           ┆           ┆           ┆          │
│ 25%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.0       ┆ 0.0       ┆ 0.0      │
│ 50%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.0       ┆ 1.0       ┆ 1.0      │
│ 75%       ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ 0.0       ┆ 1.0       ┆ 1.0      │
│ max       ┆ 2023-12-2 ┆ ZZZ       ┆ vTv Thera ┆ … ┆ 2033-03-0 ┆ 1.0       ┆ 1.0       ┆ 1.0      │
│           ┆ 9         ┆           ┆ peutics   ┆   ┆ 1         ┆           ┆           ┆          │
│           ┆           ┆           ┆ Inc.      ┆   ┆           ┆           ┆           ┆          │
│           ┆           ┆           ┆ Class A … ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [38]:
symbols_10may2023 = (
    df_master
    .filter(pl.col("date") == "2023-05-10")
    .select("symbol_15")
    .unique()
)
print(symbols_10may2023)

shape: (11_508, 1)
┌───────────┐
│ symbol_15 │
│ ---       │
│ str       │
╞═══════════╡
│ BANF      │
│ CEFA      │
│ TECH      │
│ WBX       │
│ EAI       │
│ …         │
│ ANEB      │
│ UAL       │
│ SBB       │
│ RACY W    │
│ MTB PRH   │
└───────────┘

In [31]:
df = pl.read_csv(
    "../data/aapl_1993.csv",
    schema_overrides={"NATBBO_IND": pl.Utf8}
)

In [32]:
df

shape: (3_163, 10)
┌────────┬────────────┬──────────┬─────────┬───┬────────┬──────┬─────┬──────┐
│ SYMBOL ┆ DATE       ┆ TIME     ┆ BID     ┆ … ┆ OFRSIZ ┆ MODE ┆ EX  ┆ MMID │
│ ---    ┆ ---        ┆ ---      ┆ ---     ┆   ┆ ---    ┆ ---  ┆ --- ┆ ---  │
│ str    ┆ str        ┆ str      ┆ f64     ┆   ┆ i64    ┆ i64  ┆ str ┆ str  │
╞════════╪════════════╪══════════╪═════════╪═══╪════════╪══════╪═════╪══════╡
│ AAPL   ┆ 1999-05-05 ┆ 8:15:34  ┆ 46.5    ┆ … ┆ 10     ┆ 12   ┆ T   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 8:54:01  ┆ 46.5625 ┆ … ┆ 10     ┆ 12   ┆ T   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 8:54:03  ┆ 46.5625 ┆ … ┆ 10     ┆ 12   ┆ T   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 9:07:12  ┆ 46.5625 ┆ … ┆ 1      ┆ 12   ┆ T   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 9:09:41  ┆ 46.5625 ┆ … ┆ 10     ┆ 12   ┆ T   ┆ null │
│ …      ┆ …          ┆ …        ┆ …       ┆ … ┆ …      ┆ …    ┆ …   ┆ …    │
│ AAPL   ┆ 1999-05-05 ┆ 15:58:59 ┆ 46.875  ┆ … ┆ 0      ┆ 12   ┆ T   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 15:59:05 ┆ 46.9375 ┆ … ┆ 0      ┆ 12   ┆ T   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 15:59:05 ┆ 0.0     ┆ … ┆ 2      ┆ 12   ┆ M   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 15:59:50 ┆ 46.875  ┆ … ┆ 0      ┆ 12   ┆ T   ┆ null │
│ AAPL   ┆ 1999-05-05 ┆ 15:59:50 ┆ 0.0     ┆ … ┆ 2      ┆ 12   ┆ M   ┆ null │
└────────┴────────────┴──────────┴─────────┴───┴────────┴──────┴─────┴──────┘

In [4]:
non_numeric_natbbo = df.filter(~pl.col("NATBBO_IND").cast(pl.Float64, strict=False).is_not_null())
non_numeric_natbbo.select("SYM_ROOT").unique()

shape: (3, 1)
┌──────────┐
│ SYM_ROOT │
│ ---      │
│ str      │
╞══════════╡
│ XOM      │
│ XBI      │
│ DPZ      │
└──────────┘

In [5]:
# df = pl.read_csv("../data/stock_sample7.csv")
# Ensure TIME_M is parsed as a datetime column with strict=False to handle invalid formats
df = df.with_columns(
    pl.col("TIME_M").str.to_time(format="%H:%M:%S%.f").alias("TIME_M")
)

# Filter rows between 9:30:00 and 16:00:00
df = df.filter(
    pl.col("TIME_M").is_between(pl.time(9, 30), pl.time(16, 0))
)

df.shape

(6532952, 14)

In [6]:
df['SYM_ROOT'].value_counts()

shape: (3, 2)
┌──────────┬─────────┐
│ SYM_ROOT ┆ count   │
│ ---      ┆ ---     │
│ str      ┆ u32     │
╞══════════╪═════════╡
│ XOM      ┆ 3738445 │
│ XBI      ┆ 2655843 │
│ DPZ      ┆ 138664  │
└──────────┴─────────┘

In [7]:
df['QU_CANCEL'].value_counts()

shape: (1, 2)
┌───────────┬─────────┐
│ QU_CANCEL ┆ count   │
│ ---       ┆ ---     │
│ str       ┆ u32     │
╞═══════════╪═════════╡
│ null      ┆ 6532952 │
└───────────┴─────────┘

# TAQ Quote - Data Dictionary
Exchange that issued the quote (EX)

Bid price (BID)

Bid size in units of trade (BIDSIZ)

Ask price (ASK)

Ask size in units of trade (ASKSIZ)

Condition of quote issued (QU_COND)

Bid exchange (BIDEX)

Ask exchange (ASKEX)

Quote Sequence Number (QU_SEQNUM)

National BBO Indicator (NATBBO_IND)

NASD BBO Indicator (NASDBBO_IND)

Quote Cancel/Correction (QU_CANCEL)

Source of Quote (QU_SOURCE)

## Quote Condition
‘R’ = Regular, two-sided open quote

‘L’ = Closed Market Maker (NASD)

‘Y’ = Regular - One Sided Quote (NASDAQ)

# single exchange
1. find the most liquid exchange ==> narrow apread
    - filter all two-sided quotes and get the narrowest average for each exchange
2. filter for liquid exchange

In [8]:
df['QU_COND'].value_counts()

shape: (2, 2)
┌─────────┬─────────┐
│ QU_COND ┆ count   │
│ ---     ┆ ---     │
│ str     ┆ u32     │
╞═════════╪═════════╡
│ O       ┆ 2       │
│ R       ┆ 6532950 │
└─────────┴─────────┘

In [9]:
# Filter for rows where QU_COND is 'R'
filtered_df = df.filter(pl.col("QU_COND") == "N")

# Create a new column 'spread' calculated as ASK - BID
filtered_df = filtered_df.with_columns((pl.col("ASK") - pl.col("BID")).alias("spread"))

# Aggregate by EX column and calculate the average spread
average_spread = (
	filtered_df
	.group_by("EX")
	.agg(pl.col("spread").mean().alias("average_spread"),
        pl.col("spread").count().alias("count"))
    .sort("count")
)

average_spread

shape: (0, 3)
┌─────┬────────────────┬───────┐
│ EX  ┆ average_spread ┆ count │
│ --- ┆ ---            ┆ ---   │
│ str ┆ f64            ┆ u32   │
╞═════╪════════════════╪═══════╡
└─────┴────────────────┴───────┘

*** EX Q (NASDAQ) has the tightest spread, also has the highest refresh. We assume we can connect directly with NASDAQ ***

for 10 May aapl stock: 
- K (Direct X) performance is very bad
- Z (BATS) performance is still reasonable
- N (NYSE)

In [10]:
filtered_df.filter(pl.col("EX").is_in(["N"]))['spread'].describe()
# filtered_df.filter(pl.col("EX").is_in(["K"]))['spread'].describe()
# filtered_df.filter(pl.col("EX").is_in(["Z"]))['spread'].describe()

shape: (2, 2)
┌────────────┬───────┐
│ statistic  ┆ value │
│ ---        ┆ ---   │
│ str        ┆ f64   │
╞════════════╪═══════╡
│ count      ┆ 0.0   │
│ null_count ┆ 0.0   │
└────────────┴───────┘

In [11]:
df.head()

shape: (5, 14)
┌────────────┬──────────────────┬─────┬────────┬───┬───────────┬───────────┬──────────┬────────────┐
│ DATE       ┆ TIME_M           ┆ EX  ┆ BID    ┆ … ┆ QU_CANCEL ┆ QU_SOURCE ┆ SYM_ROOT ┆ SYM_SUFFIX │
│ ---        ┆ ---              ┆ --- ┆ ---    ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---        │
│ str        ┆ time             ┆ str ┆ f64    ┆   ┆ str       ┆ str       ┆ str      ┆ str        │
╞════════════╪══════════════════╪═════╪════════╪═══╪═══════════╪═══════════╪══════════╪════════════╡
│ 2023-06-21 ┆ 09:30:00.0062343 ┆ J   ┆ 317.99 ┆ … ┆ null      ┆ C         ┆ DPZ      ┆ null       │
│            ┆ 68               ┆     ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2023-06-21 ┆ 09:30:00.0129904 ┆ T   ┆ 317.99 ┆ … ┆ null      ┆ C         ┆ DPZ      ┆ null       │
│            ┆ 64               ┆     ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2023-06-21 ┆ 09:30:00.0328076 ┆ T   ┆ 317.99 ┆ … ┆ null      ┆ C         ┆ DPZ      ┆ null       │
│            ┆ 80               ┆     ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2023-06-21 ┆ 09:30:00.0333992 ┆ B   ┆ 255.99 ┆ … ┆ null      ┆ C         ┆ DPZ      ┆ null       │
│            ┆ 96               ┆     ┆        ┆   ┆           ┆           ┆          ┆            │
│ 2023-06-21 ┆ 09:30:00.0825510 ┆ V   ┆ 256.97 ┆ … ┆ null      ┆ C         ┆ DPZ      ┆ null       │
│            ┆ 40               ┆     ┆        ┆   ┆           ┆           ┆          ┆            │
└────────────┴──────────────────┴─────┴────────┴───┴───────────┴───────────┴──────────┴────────────┘

In [12]:
df.with_columns(
    pl.when(
                (pl.col("TIME_M") < pl.time(*(10, 35, 865))) |
                (pl.col("TIME_M") < pl.time(*(12, 35, 865))) 
            )
    .then(0)
    )

shape: (6_532_952, 15)
┌────────────┬────────────────────┬─────┬────────┬───┬───────────┬──────────┬────────────┬─────────┐
│ DATE       ┆ TIME_M             ┆ EX  ┆ BID    ┆ … ┆ QU_SOURCE ┆ SYM_ROOT ┆ SYM_SUFFIX ┆ literal │
│ ---        ┆ ---                ┆ --- ┆ ---    ┆   ┆ ---       ┆ ---      ┆ ---        ┆ ---     │
│ str        ┆ time               ┆ str ┆ f64    ┆   ┆ str       ┆ str      ┆ str        ┆ i32     │
╞════════════╪════════════════════╪═════╪════════╪═══╪═══════════╪══════════╪════════════╪═════════╡
│ 2023-06-21 ┆ 09:30:00.006234368 ┆ J   ┆ 317.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 09:30:00.012990464 ┆ T   ┆ 317.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 09:30:00.032807680 ┆ T   ┆ 317.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 09:30:00.033399296 ┆ B   ┆ 255.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 09:30:00.082551040 ┆ V   ┆ 256.97 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ null    │
│ …          ┆ …                  ┆ …   ┆ …      ┆ … ┆ …         ┆ …        ┆ …          ┆ …       │
│ 2023-06-21 ┆ 15:59:59.998444800 ┆ M   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 15:59:59.998594816 ┆ Z   ┆ 103.86 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 15:59:59.998669824 ┆ U   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 15:59:59.998690048 ┆ U   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ null    │
│ 2023-06-21 ┆ 15:59:59.999837696 ┆ N   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ null    │
└────────────┴────────────────────┴─────┴────────┴───┴───────────┴──────────┴────────────┴─────────┘

In [13]:
df.with_columns(
    pl.when(
        (pl.col("TIME_M") < pl.time(10, 35)) |
        (pl.col("TIME_M") > pl.time(12, 35))
    )
    .then(pl.lit(0))
    .alias("FILTER_FLAG")
)

shape: (6_532_952, 15)
┌────────────┬────────────────┬─────┬────────┬───┬───────────┬──────────┬────────────┬─────────────┐
│ DATE       ┆ TIME_M         ┆ EX  ┆ BID    ┆ … ┆ QU_SOURCE ┆ SYM_ROOT ┆ SYM_SUFFIX ┆ FILTER_FLAG │
│ ---        ┆ ---            ┆ --- ┆ ---    ┆   ┆ ---       ┆ ---      ┆ ---        ┆ ---         │
│ str        ┆ time           ┆ str ┆ f64    ┆   ┆ str       ┆ str      ┆ str        ┆ i32         │
╞════════════╪════════════════╪═════╪════════╪═══╪═══════════╪══════════╪════════════╪═════════════╡
│ 2023-06-21 ┆ 09:30:00.00623 ┆ J   ┆ 317.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ 0           │
│            ┆ 4368           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 09:30:00.01299 ┆ T   ┆ 317.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ 0           │
│            ┆ 0464           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 09:30:00.03280 ┆ T   ┆ 317.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ 0           │
│            ┆ 7680           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 09:30:00.03339 ┆ B   ┆ 255.99 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ 0           │
│            ┆ 9296           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 09:30:00.08255 ┆ V   ┆ 256.97 ┆ … ┆ C         ┆ DPZ      ┆ null       ┆ 0           │
│            ┆ 1040           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ …          ┆ …              ┆ …   ┆ …      ┆ … ┆ …         ┆ …        ┆ …          ┆ …           │
│ 2023-06-21 ┆ 15:59:59.99844 ┆ M   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ 0           │
│            ┆ 4800           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 15:59:59.99859 ┆ Z   ┆ 103.86 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ 0           │
│            ┆ 4816           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 15:59:59.99866 ┆ U   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ 0           │
│            ┆ 9824           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 15:59:59.99869 ┆ U   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ 0           │
│            ┆ 0048           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
│ 2023-06-21 ┆ 15:59:59.99983 ┆ N   ┆ 103.87 ┆ … ┆ C         ┆ XOM      ┆ null       ┆ 0           │
│            ┆ 7696           ┆     ┆        ┆   ┆           ┆          ┆            ┆             │
└────────────┴────────────────┴─────┴────────┴───┴───────────┴──────────┴────────────┴─────────────┘

In [14]:
# df.head(100).to_pandas().plot.line(x="QU_SEQNUM", y="OBI")

In [15]:
del filtered_df
del average_spread

# Data prep
1. filter trading hours
2. Nasdaq quotes
3. take twosided quotes only

In [16]:
# filter trading hours
# df = df.with_columns(
#     pl.col("TIME_M").str.to_time(format="%H:%M:%S%.f").alias("TIME_M")
# )
df = df.filter(pl.col("SYM_ROOT") == "AAPL")
df = df.filter(
    pl.col("TIME_M").is_between(pl.time(10, 30), pl.time(12, 0))
)
# Filter for Nasdaq exchange
df = df.filter(pl.col("EX") == "N")
# Filter for rows where QU_COND is 'R'
df = df.filter(pl.col("QU_COND") == "R")
df.shape

(0, 14)

In [17]:
df.head()

shape: (0, 14)
┌──────┬────────┬─────┬─────┬───┬───────────┬───────────┬──────────┬────────────┐
│ DATE ┆ TIME_M ┆ EX  ┆ BID ┆ … ┆ QU_CANCEL ┆ QU_SOURCE ┆ SYM_ROOT ┆ SYM_SUFFIX │
│ ---  ┆ ---    ┆ --- ┆ --- ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---        │
│ str  ┆ time   ┆ str ┆ f64 ┆   ┆ str       ┆ str       ┆ str      ┆ str        │
╞══════╪════════╪═════╪═════╪═══╪═══════════╪═══════════╪══════════╪════════════╡
└──────┴────────┴─────┴─────┴───┴───────────┴───────────┴──────────┴────────────┘

In [18]:
df.describe()

shape: (9, 15)
┌────────────┬──────┬────────┬──────┬───┬───────────┬───────────┬──────────┬────────────┐
│ statistic  ┆ DATE ┆ TIME_M ┆ EX   ┆ … ┆ QU_CANCEL ┆ QU_SOURCE ┆ SYM_ROOT ┆ SYM_SUFFIX │
│ ---        ┆ ---  ┆ ---    ┆ ---  ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---        │
│ str        ┆ str  ┆ str    ┆ str  ┆   ┆ str       ┆ str       ┆ str      ┆ str        │
╞════════════╪══════╪════════╪══════╪═══╪═══════════╪═══════════╪══════════╪════════════╡
│ count      ┆ 0    ┆ 0      ┆ 0    ┆ … ┆ 0         ┆ 0         ┆ 0        ┆ 0          │
│ null_count ┆ 0    ┆ 0      ┆ 0    ┆ … ┆ 0         ┆ 0         ┆ 0        ┆ 0          │
│ mean       ┆ null ┆ null   ┆ null ┆ … ┆ null      ┆ null      ┆ null     ┆ null       │
│ std        ┆ null ┆ null   ┆ null ┆ … ┆ null      ┆ null      ┆ null     ┆ null       │
│ min        ┆ null ┆ null   ┆ null ┆ … ┆ null      ┆ null      ┆ null     ┆ null       │
│ 25%        ┆ null ┆ null   ┆ null ┆ … ┆ null      ┆ null      ┆ null     ┆ null       │
│ 50%        ┆ null ┆ null   ┆ null ┆ … ┆ null      ┆ null      ┆ null     ┆ null       │
│ 75%        ┆ null ┆ null   ┆ null ┆ … ┆ null      ┆ null      ┆ null     ┆ null       │
│ max        ┆ null ┆ null   ┆ null ┆ … ┆ null      ┆ null      ┆ null     ┆ null       │
└────────────┴──────┴────────┴──────┴───┴───────────┴───────────┴──────────┴────────────┘

In [19]:
df['NATBBO_IND'].value_counts()

shape: (0, 2)
┌────────────┬───────┐
│ NATBBO_IND ┆ count │
│ ---        ┆ ---   │
│ str        ┆ u32   │
╞════════════╪═══════╡
└────────────┴───────┘

### National Best Bid-Offer (NBBO) - Legend 
‘0’ = No National BBO change - Current quote does not affect the BBO. No National appendage is required.

‘1’ = No National BBO Can be Calculated- The National BBO cannot be calculated therefore vendors should show National BBO fields as blank. No Appendage is required.

‘2’ = Short Form National BBO Appendage Attached – A new National BBO was generated as a result of the UTP participant’s quote update and the new information is contained in the short form appendage (NBBO FILE)

‘3’ = Long Format of National BBO Appendage - A new National BBO is generated and the new BBO information is contained in the Long National BBO appendage (NBBO FILE)

‘4’ = Quote Contains all NASD BBO Information - Current quote is itself the new NASD BBO. No NASD appendage is required.

---
In the case above, I will track all bid offer and size regardless of NATBBO indicator

In [20]:
df['QU_COND'].value_counts()

shape: (0, 2)
┌─────────┬───────┐
│ QU_COND ┆ count │
│ ---     ┆ ---   │
│ str     ┆ u32   │
╞═════════╪═══════╡
└─────────┴───────┘

In [21]:
df.glimpse

<bound method DataFrame.glimpse of shape: (0, 14)
┌──────┬────────┬─────┬─────┬───┬───────────┬───────────┬──────────┬────────────┐
│ DATE ┆ TIME_M ┆ EX  ┆ BID ┆ … ┆ QU_CANCEL ┆ QU_SOURCE ┆ SYM_ROOT ┆ SYM_SUFFIX │
│ ---  ┆ ---    ┆ --- ┆ --- ┆   ┆ ---       ┆ ---       ┆ ---      ┆ ---        │
│ str  ┆ time   ┆ str ┆ f64 ┆   ┆ str       ┆ str       ┆ str      ┆ str        │
╞══════╪════════╪═════╪═════╪═══╪═══════════╪═══════════╪══════════╪════════════╡
└──────┴────────┴─────┴─────┴───┴───────────┴───────────┴──────────┴────────────┘>

In [22]:
df.columns

['DATE',
 'TIME_M',
 'EX',
 'BID',
 'BIDSIZ',
 'ASK',
 'ASKSIZ',
 'QU_COND',
 'QU_SEQNUM',
 'NATBBO_IND',
 'QU_CANCEL',
 'QU_SOURCE',
 'SYM_ROOT',
 'SYM_SUFFIX']

# Try OBI strategy

In [23]:
class OBIVWAPStrategy:
    def __init__(self, vwap_window: int, obi_threshold: float, initial_cash: float = 100_000):
        self.vwap_window = vwap_window
        self.obi_threshold = obi_threshold
        self.cash = initial_cash
        self.position = 0
        self.account_balance = []

    def calculate_vwap(self, df: pl.DataFrame) -> pl.DataFrame:
        # Calculate MID_PRICE
        df = df.with_columns(
            ((pl.col("BID") + pl.col("ASK")) / 2).alias("MID_PRICE")
        )
        # Calculate Volume
        df = df.with_columns(
            (pl.col("BIDSIZ") + pl.col("ASKSIZ")).alias("Volume")
        )
        # Calculate VWAP using rolling window
        df = df.with_columns(
            (
                (pl.col("MID_PRICE") * pl.col("Volume"))
                .rolling_sum(window_size=self.vwap_window)
                / pl.col("Volume").rolling_sum(window_size=self.vwap_window)
            ).alias("VWAP")
        )
        return df

    def calculate_obi(self, df: pl.DataFrame) -> pl.DataFrame:
        # Calculate Order Book Imbalance (OBI)
        df = df.with_columns(
            (
                (pl.col("BIDSIZ") - pl.col("ASKSIZ"))
                / (pl.col("BIDSIZ") + pl.col("ASKSIZ"))
            ).alias("OBI")
        )
        return df

    def generate_signals(self, df: pl.DataFrame) -> pl.DataFrame:
        # Calculate VWAP and OBI
        df = self.calculate_vwap(df)
        df = self.calculate_obi(df)

        # Generate signals based on OBI threshold
        df = df.with_columns(
            pl.when(pl.col("OBI") > self.obi_threshold)
            .then(1)  # Buy signal
            .when(pl.col("OBI") < -self.obi_threshold)
            .then(-1)  # Sell signal
            .otherwise(0)  # No signal
            .alias("Signal")
        )
        return df

    def backtest(self, df: pl.DataFrame) -> pl.DataFrame:
        # Initialize account balance tracking
        account_balance = []

        # Iterate over rows to simulate trading
        for row in df.iter_rows(named=True):
            if row["Signal"] == 1 and self.cash >= row["ASK"] * 100 and self.position <= 1:
                # Buy 100 shares
                self.position = 100
                self.cash -= row["ASK"] * 100
            elif row["Signal"] == -1 and self.position > -1:
                # Sell 100 shares
                self.position = -100
                self.cash += row["BID"] * 100
            elif row["Signal"] == 0 and self.position != 0:
                # Close position
                if self.position > 0:
                    self.cash += row["BID"] * self.position
                else:
                    self.cash -= row["ASK"] * abs(self.position)
                self.position = 0

            # Record account balance
            account_balance.append(self.cash + self.position * (row["ASK"] if self.position > 0 else row["BID"]))

        # Add account balance to the DataFrame
        df = df.with_columns(pl.Series("Account_Balance", account_balance))
        return df

In [24]:
strategy = OBIVWAPStrategy(vwap_window=50, obi_threshold=0.2)
signal_data = strategy.generate_signals(df)
backtest_data = strategy.backtest(signal_data)

print(backtest_data.head())

shape: (0, 20)
┌──────┬────────┬─────┬─────┬───┬──────┬─────┬────────┬─────────────────┐
│ DATE ┆ TIME_M ┆ EX  ┆ BID ┆ … ┆ VWAP ┆ OBI ┆ Signal ┆ Account_Balance │
│ ---  ┆ ---    ┆ --- ┆ --- ┆   ┆ ---  ┆ --- ┆ ---    ┆ ---             │
│ str  ┆ time   ┆ str ┆ f64 ┆   ┆ f64  ┆ f64 ┆ i32    ┆ null            │
╞══════╪════════╪═════╪═════╪═══╪══════╪═════╪════════╪═════════════════╡
└──────┴────────┴─────┴─────┴───┴──────┴─────┴────────┴─────────────────┘

In [25]:
backtest_data["Account_Balance"].describe()

shape: (2, 2)
┌────────────┬───────┐
│ statistic  ┆ value │
│ ---        ┆ ---   │
│ str        ┆ f64   │
╞════════════╪═══════╡
│ count      ┆ 0.0   │
│ null_count ┆ 0.0   │
└────────────┴───────┘

In [26]:
backtest_data.columns

['DATE',
 'TIME_M',
 'EX',
 'BID',
 'BIDSIZ',
 'ASK',
 'ASKSIZ',
 'QU_COND',
 'QU_SEQNUM',
 'NATBBO_IND',
 'QU_CANCEL',
 'QU_SOURCE',
 'SYM_ROOT',
 'SYM_SUFFIX',
 'MID_PRICE',
 'Volume',
 'VWAP',
 'OBI',
 'Signal',
 'Account_Balance']

In [27]:
# df_tmp = backtest_data.filter(pl.col("VWAP").is_not_null())

In [28]:
backtest_data['OBI'].describe()

shape: (2, 2)
┌────────────┬───────┐
│ statistic  ┆ value │
│ ---        ┆ ---   │
│ str        ┆ f64   │
╞════════════╪═══════╡
│ count      ┆ 0.0   │
│ null_count ┆ 0.0   │
└────────────┴───────┘

In [29]:
df_tmp = backtest_data.filter(pl.col("VWAP").is_not_null())
df_tmp

shape: (0, 20)
┌──────┬────────┬─────┬─────┬───┬──────┬─────┬────────┬─────────────────┐
│ DATE ┆ TIME_M ┆ EX  ┆ BID ┆ … ┆ VWAP ┆ OBI ┆ Signal ┆ Account_Balance │
│ ---  ┆ ---    ┆ --- ┆ --- ┆   ┆ ---  ┆ --- ┆ ---    ┆ ---             │
│ str  ┆ time   ┆ str ┆ f64 ┆   ┆ f64  ┆ f64 ┆ i32    ┆ null            │
╞══════╪════════╪═════╪═════╪═══╪══════╪═════╪════════╪═════════════════╡
└──────┴────────┴─────┴─────┴───┴──────┴─────┴────────┴─────────────────┘

In [30]:
df_tmp[['QU_SEQNUM', 'OBI']].head(1000).plot.line(x="QU_SEQNUM", y="OBI")

ModuleUpgradeRequiredError: altair>=5.4.0 is required for `.plot`

In [ ]:
df_tmp[['QU_SEQNUM', 'MID_PRICE']].head(1000).plot.line(x="QU_SEQNUM", y="MID_PRICE")

alt.Chart(...)

In [ ]:
df_tmp[['QU_SEQNUM', 'VWAP']].head(1000).plot.line(x="QU_SEQNUM", y="VWAP")

alt.Chart(...)

In [ ]:
df_tmp.head(100).to_pandas().plot.line(x="QU_SEQNUM", y="OBI")

ArrowInvalid: Value 37800048115245 has non-zero nanoseconds

In [ ]:
df_tmp.head(2000).plot.line(x="TIME_M", y="MID_PRICE")

ValueError: Unexpected DtypeKind: Time

alt.Chart(...)

In [ ]:
df_tmp.head(2000).plot.line(x="TIME_M", y="OBI")

ValueError: Unexpected DtypeKind: Time

alt.Chart(...)

In [ ]:
df_tmp.head(2000).

SyntaxError: invalid syntax (3424061299.py, line 1)

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Convert to pandas
backtest_data = backtest_data.with_columns(
    (pl.col("DATE").cast(pl.Utf8) + " " + pl.col("TIME_M").cast(pl.Utf8))
    .str.strptime(pl.Datetime("ns"), format="%Y-%m-%d %H:%M:%S%.f")
    .alias("TIME_M")
)

pdf = backtest_data.to_pandas()


# Plot
for ticker in set(pdf['SYM_ROOT']):
    ticker_df = pdf[pdf['SYM_ROOT'] == ticker]
    plt.figure(figsize=(12, 6))
    plt.plot(ticker_df["TIME_M"], ticker_df["Account_Balance"])
    plt.xlabel("TIME_M")
    plt.ylabel("Account_Balance")
    plt.title(f"Account Balance for {ticker}")
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m-%d %H:%M'))
    plt.xticks(rotation=45)
    plt.show()

InvalidOperationError: conversion from `str` to `datetime[ns]` failed in column 'DATE' for 346766 out of 346766 values: ["2023-05-11 2023-05-11 10:30:00.000000000", "2023-05-11 2023-05-11 10:30:00.000000000", … "2023-05-11 2023-05-11 11:59:59.000000000"]

You might want to try:
- setting `strict=False` to set values that cannot be converted to `null`
- using `str.strptime`, `str.to_date`, or `str.to_datetime` and providing a format string